import Mainlayout from '@/components/mainlayout'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: any) {
  return (
    <html lang="en">
      <body  suppressHydrationWarning={true} className='bg-[#ECECEC] overflow-x-hidden'>
        <Mainlayout>{children}</Mainlayout>
      </body>
    </html>
  )
}
